### ISSUE TITLE
Increase project maintainability

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/eks-operator#91]
This epic will track tasks for increasing project maintainability:

- [x] Enable github workflows for this repository
- [x] Add golang-ci lint workflow
- [x] #92
- [x] Add new task to makefile for building operator binary
- [x] Create AWS services mocks to use for unit tests
- [x] Set up a basic unit test suite
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100
